apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.nexusNs }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.cloudwatchNs }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.externaldnsNs }}
---
