apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.Version }}.{{ .Release.Name }}-ebs-claim
  namespace: {{ .Values.namespaces.nexusNs }}
spec:
  accessModes:
    - {{ .Values.pvc.accessModes }}
  storageClassName: local-storage
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}