apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: {{ .Values.namespaces.nexusNs }}
  name: {{ .Chart.Name }}-{{ .Chart.Version }}.{{ .Release.Name }}-secret
spec:
  provider: aws
  secretObjects:
  - data:
    - key: db-user
      objectName: nxrm-db-user
    - key: db-password
      objectName: nxrm-db-password
    - key: db-host
      objectName: nxrm-db-host
    secretName: nxrm-db-secret
    type: Opaque
  - data:
    - key: nexus-admin-password
      objectName: nxrm-admin-password
    secretName: nxrm-admin-secret
    type: Opaque
  parameters:
    objects:  |
        - objectName: "{{ .Values.secret.license.arn }}"
          objectAlias: "{{ .Values.secret.license.alias }}"
        - objectName: "{{ .Values.secret.rds.arn }}"
          jmesPath:
            - path: "username"
              objectAlias: "nxrm-db-user"
            - path: "password"
              objectAlias: "nxrm-db-password"
            - path: "host"
              objectAlias: "nxrm-db-host"
        - objectName: "{{ .Values.secret.adminpassword.arn }}"
          jmesPath:
           - path: "admin_nxrm_password"
             objectAlias: "nxrm-admin-password"
