apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.Version }}.{{ .Release.Name }}-ebs-pv2
spec:
  capacity:
    storage: {{ .Values.pv.storage }}
  volumeMode: Filesystem
  accessModes:
  - {{ .Values.pv.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.pv.reclaimPolicy }}
  storageClassName: local-storage
  local:
    path: {{ .Values.pv.path2 }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          {{- range $zone  := .Values.pv.zones }}
          - {{ $zone }} 
          {{- end }}  

          
          
         