apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespaces.nexusNs }}
  labels:
    app: nxrm
spec:
  type: {{ .Values.service.nexus.type }}
  selector:
    app: nxrm
  ports:
    - protocol: {{ .Values.service.nexus.protocol }}
      port: {{ .Values.service.nexus.port }}
      targetPort: {{ .Values.service.nexus.targetPort }}
---
{{- if .Values.service.docker.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-docker-service
  namespace: {{ .Values.namespaces.nexusNs }}
  labels:
    app: nxrm
spec:
  type:  {{ .Values.service.docker.type }}
  selector:
    app: nxrm
  ports:
    - name: docker-service
      protocol: {{ .Values.service.docker.protocol }}
      port: {{ .Values.service.docker.port }}
      targetPort: {{ .Values.service.docker.targetPort }}
{{- end }}
