apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ .Chart.Name }}-{{ .Chart.Version}}-{{ .Release.Name }}-ebs-storage"
  namespace: {{ .Values.namespaces.nexusNs }}
provisioner: {{ .Values.storageClass.provisioner }}
volumeBindingMode: WaitForFirstConsumer
