apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ .Values.storageClass.name }}"
  namespace: {{ .Values.namespaces.nexusNs }}
provisioner: {{ .Values.pv.provisioner }}
volumeBindingMode: WaitForFirstConsumer
