apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ .Values.storageClass.name }}"
  namespace: {{ .Values.namespaces.nexusNs }}
provisioner: {{ ternary .Values.pv.staticProvisioner .Values.pv.dynamicProvisioner (eq .Values.pv.mode "static") }}
volumeBindingMode: WaitForFirstConsumer
