apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: nxrm
  name: nxrm-nexus-secret
spec:
  provider: azure
  secretObjects:
  - data:
    - key: db-user
      objectName: nxrm-db-user
    - key: db-password
      objectName: nxrm-db-password
    - key: db-host
      objectName: nxrm-db-host
    secretName: nxrm-db-secret
    type: Opaque
  - data:
    - key: nexus-admin-password
      objectName: nxrm-admin-password
    secretName: nxrm-admin-secret
    type: Opaque
  parameters:
    keyvaultName: keyvaultname
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "dcf99d84-bd2e-4f51-82cc-e32a96a3349c"
    objects: |
      array:
        - |
          objectName: nxrm-license.lic
          objectType: secret
          objectEncoding: base64
        - |
          objectName: nxrm-db-password
          objectType: secret
        - |
          objectName: nxrm-db-user
          objectType: secret
        - |
          objectName: nxrm-db-host
          objectType: secret
        - |
          objectName: nxrm-admin-password
          objectType: secret
    tenantId: "tenantId"
