apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: {{ .Values.namespaces.nexusNs }}
  name: {{ .Chart.Name }}-{{ .Chart.Version }}.{{ .Release.Name }}-secret
spec:
  provider: {{ .Values.secret.provider}}
  secretObjects:
  - data:
    - key: db-user
      objectName: {{.Values.secret.db.user}}
    - key: db-password
      objectName: {{.Values.secret.db.password}}
    - key: db-host
      objectName: {{.Values.secret.db.host}}
    secretName: nxrm-db-secret
    type: Opaque
  - data:
    - key: nexus-admin-password
      objectName: {{.Values.secret.adminPassword}}
    secretName: nxrm-admin-secret
    type: Opaque
  parameters:
    keyvaultName: {{.Values.secret.keyvaultName}}
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "dcf99d84-bd2e-4f51-82cc-e32a96a3349c"
    objects: |
      array:
        - |
          objectName: {{ .Values.secret.license.name }}
          objectType: secret
          objectEncoding: base64
        - |
          objectName: {{.Values.secret.db.password}}
          objectType: secret
        - |
          objectName: {{.Values.secret.db.user}}
          objectType: secret
        - |
          objectName: {{.Values.secret.db.host}}
          objectType: secret
        - |
          objectName: {{.Values.secret.adminPassword}}
          objectType: secret

    tenantId: { { .Values.secret.tenantId } }
