apiVersion: v1
kind: PersistentVolume
metadata:
  name: nxrm-local-disk-pv
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /nexus-repo-mgr-work-dir/work
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          {{- range $zone  := .Values.pv.zones }}
          - {{ $zone }} 
          {{- end }}
