apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nxrm-local-disk-claim
  namespace: nxrm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 20Gi