apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: nxrm
  name: nxrm-docker-ingress
  annotations:
    kubernetes.io/ingress.class: nginx #Add more annotations as needed
spec:
  rules:
    - host: example.com #comment out if not using https for load balancer
      http:
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nxrm-docker-service
            port:
              number: 9090
