# Copyright Sonatype, Inc., 2022, All Rights Reserved.
#
# Note: This YAML file is just an example and cannot be used as-is.
# You must fill it out with the appropriate information for your deployment to be able to use it.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nxrm-local-disk-pv-1
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nxrm-local-storage
  local:
    path: /nexus-repo-mgr-work-dir/work1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/hostname
          operator: In
          values:
            - example-node
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nxrm-local-disk-pv-2
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nxrm-local-storage
  local:
    path: /nexus-repo-mgr-work-dir/work2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/hostname
              operator: In
              values:
                - example-node
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nxrm-local-disk-pv-3
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nxrm-local-storage
  local:
    path: /nexus-repo-mgr-work-dir/work3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/hostname
              operator: In
              values:
                - example-node
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nxrm-local-disk-pv-4
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nxrm-local-storage
  local:
    path: /nexus-repo-mgr-work-dir/work4
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/hostname
              operator: In
              values:
                - example-node
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nxrm-local-disk-pv-5
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nxrm-local-storage
  local:
    path: /nexus-repo-mgr-work-dir/work5
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/hostname
              operator: In
              values:
                - example-node
